name: Github Actions Tests
on:
  [push, pull_request]
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running tests..."
      - run: echo "${{ github.event_name }}"
      - run: echo "Tests completed successfully!"
